import { Flow } from '../types'

export const mockFlows: Flow[] = [
  {
    id: 'flow-001',
    timestamp: new Date(Date.now() - 1000).toISOString(),
    duration: 45,
    srcIp: '10.244.0.15',
    srcPort: 45678,
    srcPod: 'frontend-7b9f5c6d4f-xk2jl',
    srcNamespace: 'production',
    dstIp: '10.96.0.100',
    dstPort: 443,
    dstPod: 'api-gateway-5d8f9c7b6a-m4np2',
    dstNamespace: 'production',
    dstService: 'api-gateway.production.svc.cluster.local',
    protocol: 'HTTPS',
    status: 'CLOSED',
    bytesSent: 2456,
    bytesReceived: 18934,
    packetsSent: 12,
    packetsReceived: 45,
    tcpHandshakeMs: 1.2,
    tlsHandshakeMs: 8.5,
    ttfbMs: 23.4,
    tls: {
      version: 'TLS 1.3',
      sni: 'api.podscope.io',
      cipherSuite: 'TLS_AES_256_GCM_SHA384',
      alpn: ['h2', 'http/1.1'],
      encrypted: true,
    },
    http: {
      method: 'POST',
      url: '/api/v1/flows/ingest',
      host: 'api.podscope.io',
      statusCode: 201,
      statusText: 'Created',
      requestHeaders: {
        'Content-Type': 'application/json',
        'Authorization': 'Bearer ***',
        'X-Request-ID': 'req-abc123',
      },
      responseHeaders: {
        'Content-Type': 'application/json',
        'X-Response-Time': '23ms',
      },
      contentType: 'application/json',
      contentLength: 256,
    },
  },
  {
    id: 'flow-002',
    timestamp: new Date(Date.now() - 2500).toISOString(),
    duration: 12,
    srcIp: '10.244.0.22',
    srcPort: 39012,
    srcPod: 'user-service-6c8d7e9f5a-pq3rs',
    srcNamespace: 'production',
    dstIp: '10.96.0.50',
    dstPort: 5432,
    protocol: 'TCP',
    status: 'CLOSED',
    bytesSent: 1024,
    bytesReceived: 8192,
    packetsSent: 8,
    packetsReceived: 24,
    tcpHandshakeMs: 0.8,
    ttfbMs: 5.2,
  },
  {
    id: 'flow-003',
    timestamp: new Date(Date.now() - 4000).toISOString(),
    duration: 156,
    srcIp: '10.244.0.15',
    srcPort: 45680,
    srcPod: 'frontend-7b9f5c6d4f-xk2jl',
    srcNamespace: 'production',
    dstIp: '35.192.78.123',
    dstPort: 443,
    dstService: 'analytics.google.com',
    protocol: 'TLS',
    status: 'CLOSED',
    bytesSent: 3456,
    bytesReceived: 1234,
    packetsSent: 15,
    packetsReceived: 8,
    tcpHandshakeMs: 35.2,
    tlsHandshakeMs: 48.7,
    ttfbMs: 112.3,
    tls: {
      version: 'TLS 1.3',
      sni: 'analytics.google.com',
      cipherSuite: 'TLS_CHACHA20_POLY1305_SHA256',
      encrypted: true,
    },
  },
  {
    id: 'flow-004',
    timestamp: new Date(Date.now() - 5500).toISOString(),
    duration: 8,
    srcIp: '10.244.0.33',
    srcPort: 52100,
    srcPod: 'cache-redis-0',
    srcNamespace: 'data',
    dstIp: '10.96.0.75',
    dstPort: 6379,
    protocol: 'TCP',
    status: 'CLOSED',
    bytesSent: 128,
    bytesReceived: 512,
    packetsSent: 4,
    packetsReceived: 6,
    tcpHandshakeMs: 0.3,
    ttfbMs: 1.1,
  },
  {
    id: 'flow-005',
    timestamp: new Date(Date.now() - 7000).toISOString(),
    duration: 234,
    srcIp: '10.244.0.15',
    srcPort: 45682,
    srcPod: 'frontend-7b9f5c6d4f-xk2jl',
    srcNamespace: 'production',
    dstIp: '10.96.0.100',
    dstPort: 80,
    dstService: 'backend-api.production.svc',
    protocol: 'HTTP',
    status: 'CLOSED',
    bytesSent: 1892,
    bytesReceived: 45678,
    packetsSent: 10,
    packetsReceived: 82,
    tcpHandshakeMs: 0.9,
    ttfbMs: 45.6,
    http: {
      method: 'GET',
      url: '/api/v2/users/profile?include=preferences,settings',
      host: 'backend-api.production.svc',
      statusCode: 200,
      statusText: 'OK',
      requestHeaders: {
        'Accept': 'application/json',
        'User-Agent': 'PodScope-Agent/1.0',
        'X-Correlation-ID': 'corr-xyz789',
      },
      responseHeaders: {
        'Content-Type': 'application/json',
        'Cache-Control': 'max-age=60',
        'X-Response-Time': '45ms',
      },
      contentType: 'application/json',
      contentLength: 45678,
      responseBody: '{"id":"usr_123","name":"John Doe","email":"john@example.com","preferences":{"theme":"dark","notifications":true}}',
    },
  },
  {
    id: 'flow-006',
    timestamp: new Date(Date.now() - 8500).toISOString(),
    duration: 3,
    srcIp: '10.244.0.22',
    srcPort: 39015,
    srcPod: 'user-service-6c8d7e9f5a-pq3rs',
    srcNamespace: 'production',
    dstIp: '10.96.0.100',
    dstPort: 80,
    dstService: 'backend-api.production.svc',
    protocol: 'HTTP',
    status: 'RESET',
    bytesSent: 256,
    bytesReceived: 0,
    packetsSent: 3,
    packetsReceived: 1,
    tcpHandshakeMs: 0.5,
    http: {
      method: 'DELETE',
      url: '/api/v2/sessions/expired',
      host: 'backend-api.production.svc',
      statusCode: 500,
      statusText: 'Internal Server Error',
      responseBody: '{"error":"connection_reset","message":"Database connection failed"}',
    },
  },
  {
    id: 'flow-007',
    timestamp: new Date(Date.now() - 10000).toISOString(),
    duration: 67,
    srcIp: '10.244.0.44',
    srcPort: 60123,
    srcPod: 'notification-worker-8f7e6d5c4b-jk9lm',
    srcNamespace: 'workers',
    dstIp: '10.96.0.200',
    dstPort: 443,
    dstService: 'smtp-relay.mail.svc',
    protocol: 'TLS',
    status: 'CLOSED',
    bytesSent: 4567,
    bytesReceived: 890,
    packetsSent: 18,
    packetsReceived: 12,
    tcpHandshakeMs: 1.1,
    tlsHandshakeMs: 12.3,
    ttfbMs: 34.5,
    tls: {
      version: 'TLS 1.2',
      sni: 'smtp-relay.mail.svc',
      cipherSuite: 'TLS_ECDHE_RSA_WITH_AES_128_GCM_SHA256',
      encrypted: true,
    },
  },
  {
    id: 'flow-008',
    timestamp: new Date(Date.now() - 12000).toISOString(),
    duration: 89,
    srcIp: '10.244.0.15',
    srcPort: 45690,
    srcPod: 'frontend-7b9f5c6d4f-xk2jl',
    srcNamespace: 'production',
    dstIp: '10.96.0.100',
    dstPort: 80,
    protocol: 'HTTP',
    status: 'CLOSED',
    bytesSent: 789,
    bytesReceived: 12345,
    packetsSent: 6,
    packetsReceived: 28,
    tcpHandshakeMs: 0.7,
    ttfbMs: 28.9,
    http: {
      method: 'PUT',
      url: '/api/v2/users/preferences',
      host: 'backend-api.production.svc',
      statusCode: 204,
      statusText: 'No Content',
      requestHeaders: {
        'Content-Type': 'application/json',
      },
      requestBody: '{"theme":"dark","language":"en"}',
    },
  },
]

export function generateMockFlow(): Flow {
  const protocols: Flow['protocol'][] = ['HTTP', 'HTTPS', 'TLS', 'TCP']
  const statuses: Flow['status'][] = ['CLOSED', 'RESET', 'TIMEOUT', 'OPEN']
  const methods = ['GET', 'POST', 'PUT', 'DELETE', 'PATCH']
  const pods = [
    'frontend-7b9f5c6d4f-xk2jl',
    'api-gateway-5d8f9c7b6a-m4np2',
    'user-service-6c8d7e9f5a-pq3rs',
    'cache-redis-0',
    'notification-worker-8f7e6d5c4b-jk9lm',
  ]
  const namespaces = ['production', 'staging', 'data', 'workers']
  const hosts = [
    'api.podscope.io',
    'backend-api.production.svc',
    'analytics.google.com',
    'cdn.cloudflare.net',
  ]

  const protocol = protocols[Math.floor(Math.random() * protocols.length)]
  const isHTTP = protocol === 'HTTP' || protocol === 'HTTPS'

  return {
    id: `flow-${Date.now()}-${Math.random().toString(36).substr(2, 9)}`,
    timestamp: new Date().toISOString(),
    duration: Math.floor(Math.random() * 500) + 10,
    srcIp: `10.244.0.${Math.floor(Math.random() * 255)}`,
    srcPort: 30000 + Math.floor(Math.random() * 35000),
    srcPod: pods[Math.floor(Math.random() * pods.length)],
    srcNamespace: namespaces[Math.floor(Math.random() * namespaces.length)],
    dstIp: `10.96.0.${Math.floor(Math.random() * 255)}`,
    dstPort: protocol === 'HTTPS' || protocol === 'TLS' ? 443 : protocol === 'HTTP' ? 80 : 5432,
    dstService: hosts[Math.floor(Math.random() * hosts.length)],
    protocol,
    status: statuses[Math.floor(Math.random() * statuses.length)],
    bytesSent: Math.floor(Math.random() * 10000) + 100,
    bytesReceived: Math.floor(Math.random() * 50000) + 500,
    packetsSent: Math.floor(Math.random() * 50) + 5,
    packetsReceived: Math.floor(Math.random() * 100) + 10,
    tcpHandshakeMs: Math.random() * 5,
    tlsHandshakeMs: protocol === 'HTTPS' || protocol === 'TLS' ? Math.random() * 50 : undefined,
    ttfbMs: Math.random() * 100 + 10,
    ...(isHTTP && {
      http: {
        method: methods[Math.floor(Math.random() * methods.length)],
        url: `/api/v${Math.floor(Math.random() * 3) + 1}/${['users', 'flows', 'sessions', 'data'][Math.floor(Math.random() * 4)]}`,
        host: hosts[Math.floor(Math.random() * hosts.length)],
        statusCode: [200, 201, 204, 400, 404, 500][Math.floor(Math.random() * 6)],
        statusText: 'OK',
      },
    }),
    ...((protocol === 'HTTPS' || protocol === 'TLS') && {
      tls: {
        version: ['TLS 1.2', 'TLS 1.3'][Math.floor(Math.random() * 2)],
        sni: hosts[Math.floor(Math.random() * hosts.length)],
        cipherSuite: 'TLS_AES_256_GCM_SHA384',
        encrypted: true,
      },
    }),
  }
}
